#!/usr/bin/env bash

version=$1
if test -z "$version";
then
	echo "PHP version is empty"
	exit 1
fi

regex="^[0-9]\.[0-9]$"
 
if [[ $version =~ $regex ]];
then
	echo "Selected php version is "$version
else
	echo "php version should be in form of X.X like 7.1"
	exit 2
fi

cd $LARADOCK
sed -i "s/PHP_VERSION=.../PHP_VERSION=$version/g" '.env'

dc-down
docker-compose build php-fpm
docker-compose build workspace
dc-up
